var bzxy =
[
    {
        school:"滨州学院",
        "major":"计算机网络技术",
        "year":2015,
        "score":440
    },
    {
        school:"滨州学院",
        "major":"计算机网络技术",
        "year":2014,
        "score":399
    },
    {
        school:"滨州学院",
        "major":"计算机网络技术",
        "year":2013,
        "score":353
    },
    {
        school:"临沂大学",
        "major":"计算机网络技术",
        "year":2015,
        "score":473
    },
    {
        school:"临沂大学",
        "major":"计算机网络技术",
        "year":2014,
        "score":460
    },
    {
        school:"临沂大学",
        "major":"计算机网络技术",
        "year":2013,
        "score":380
    },
    {
        school:"泰山学院",
        "major":"计算机应用技术",
        "year":2015,
        "score":465
    },
    {
        school:"泰山学院",
        "major":"计算机应用技术",
        "year":2014,
        "score":460
    },
    {
        school:"泰山学院",
        "major":"计算机应用技术",
        "year":2013,
        "score":465
    },
    {
        school:"齐鲁理工学院(所有专业平均分,没有专业的)",
        "major":"计算机应用技术",
        "year":2015,
        "score":455
    },
    {
        school:"齐鲁理工学院(所有专业平均分,没有专业的)",
        "major":"计算机应用技术",
        "year":2014,
        "score":470
    },
    {
        school:"齐鲁理工学院(所有专业平均分,没有专业的)",
        "major":"计算机应用技术",
        "year":2013,
        "score":476
    }
];
module.exports = bzxy;
